spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: auth-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JeongUijeong/microblog-config-repo.git
          default-label: main
          timeout: 5 # 연결 대기 5초
          clone-on-start: true
          search-paths: .
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
